server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/

spring:
  application:
    name: service-redis
  redis: # Redis
    database: 0
    host: 47.101.130.148 #远程服务器redis
    port: 6379 #redis端口号
    password: lv85208520 #redis密码
    timeout: 120000
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 5
        min-idle: 3
