
server:
  port: 9001

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/static/Manager/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/public/,classpath:/upload
  data:
    mongodb:
      uri: mongodb://47.101.130.148:27017/news
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  #spring:
  application:
    name: consumer

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instance-id: microservice-consumer-9001
    prefer-ip-address: true     #访问路径可以显示IP地址
