server:
  port: 8002

#整合mybatisplus
mybatis-plus:
  type-aliases-package: com.cssl.entity
  global-config:
    db-config:
      id-type: auto #全局主键自增
      field-strategy: not_empty #字段策略 0:"忽略判断" 1."非null判断" 2.非空判断
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      refresh: true #刷新mapper 调试神器
  configuration:
    map-underscore-to-camel-case: false #驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper-locations: classpath:mapper/*.xml

spring:
  application:
    #微服务名
    name: service-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.130.148:3306/guomei?serverTimezone=GMT
    username: guomei
    password: lv85208520
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  data:
    mongodb:
      uri: mongodb://47.101.130.148:27017/news
    solr:
        host: http://127.0.0.1:8983/solr/mycore
        #host: http://127.0.0.1:8983/solr  #使用模板

  #用于分布式存储
  redis:
    port: 6379
    database: 0
    host: 47.101.130.148
    password: lv85208520
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6001/eureka/
      #Eureka服务器集群
      #defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instance-id: service-product8002
    prefer-ip-address: true     #访问路径可以显示IP地址
    leaseRenewalIntervalInSeconds: 10   #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 30 #租期到期时间（默认90秒）

info:
  app.name: cssl-microservice
  company.name: www.cssl.com
  build.artifactId: microservice
  build.version: 1.0-SNAPSHOT

#spring:
#  boot:
#    admin:
#      client:
#        url: "http://localhost:8000"

#启用监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - "*" # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
#  endpoint:
#    health:
#      show-details: always #未开启actuator/health时，我们获取到的信息是{"status":"UP"}，status的值还有可能是 DOWN。开启后打印详细信息

